config/routes.rb
Rails.application.routes.draw do
  get 'actors/new'
  get 'actors/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :tv_shows do
    resources :episodes
    resources :actors, only: [:new, :create]
  end
  
  root 'tv_shows#index'
 
end

app/models/actor.rb
class Actor < ApplicationRecord
    has_and_belongs_to_many :tv_shows, dependent: :destroy
    has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :tv_show
end

app/models/film_location.rb
class FilmLocation < ApplicationRecord
  belongs_to :tv_show
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :genre_tv_shows, dependent: :destroy
    has_many :tv_shows, through: :genre_tv_shows
end

app/models/genre_tv_show.rb
class GenreTvShow < ApplicationRecord
  belongs_to :genre
  belongs_to :tv_show
end

app/models/genre_tv_shows.rb
class GenreTvShow < ApplicationRecord
    belongs_to :genre
    belongs_to :tv_show
end

app/models/nationality.rb
class Nationality < ApplicationRecord
    has_many :tv_shows, dependent: :destroy
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    has_and_belongs_to_many :actors, dependent: :destroy
    has_many :genre_tv_shows, dependent: :destroy
    has_many :genres, through: :genre_tv_shows
    belongs_to :nationality
    belongs_to :user
    has_many :episodes, dependent: :destroy
    has_many :film_locations, dependent: :destroy, inverse_of: :tv_show
    accepts_nested_attributes_for :film_locations
    
    validates :name, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tv_shows, dependent: :destroy
  has_one_attached :image
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def new
    @tv_show = TvShow.find(params[:tv_show_id])
    @actor = @tv_show.actors.build
  end

  def create
      @tv_show = TvShow.find(params[:tv_show_id])
      @actor = @tv_show.actors.create!(actor_params)
      redirect_to @tv_show
  end

  private

  def actor_params
    params.require(:actor).permit(:first_name, :last_name, :age, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
    def create
      @tv_show = TvShow.find(params[:tv_show_id])
      @episode = @tv_show.episodes.create(episode_params)
      redirect_to tv_show_path(@tv_show)
    end
  
    private
    def episode_params
        params.require(:episode).permit(:episode_number, :title, :summary)
    end
  end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tv_show, only: %i[ show edit update destroy ]

  # GET /tv_shows or /tv_shows.json
  def index
    @tv_shows = TvShow.all
  end

  # GET /tv_shows/1 or /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
    2.times { @tv_show.film_locations.build }
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows or /tv_shows.json
  def create
    @tv_show = current_user.tv_shows.build(tv_show_params)
    @tv_show.nationality = Nationality.find(params[:tv_show][:nationality_id]) || Nationality.last

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully created." }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1 or /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to tv_show_url(@tv_show), notice: 'Tv show was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1 or /tv_shows/1.json
  def destroy
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: "Tv show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tv_show_params
      params.require(:tv_show).permit(
        :name,
        :summary,
        :release_date,
        :nationality_id,
        film_locations_attributes: [:id, :name, :indoor],
        genre_ids: []
        )
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/actors/create.html.erb
<h1>Actors create</h1>
<p>Find me in app/views/actors/create.html.erb</p>

app/views/actors/new.html.erb
<!--app/views/actors/new.html.erb-->
<div>
<button><%= link_to 'Home', tv_shows_path%></button>
</div>
<div class="New_movies z">
<h1 class="titulo">Add Actors to Movies</h1>

<%= form_with(model:[@tv_show, @actor]) do |form| %>
    <div class="field">
        <%= form.label :first_name, :class=>"tx" %>
        <%= form.text_field :first_name, :class=>"fondo" %>
    </div>

    <div class="field">
        <%= form.label :last_name, :class=>"tx" %>
        <%= form.text_field :last_name, :class=>"fondo" %>
    </div>

    <div class="field">
        <%= form.label :age, :class=>"tx" %>
        <%= form.number_field :age, :class=>"fondo" %>
    </div>

    <div class="field">
        <%= form.label :image, :class=>"tx" %>
        <%= form.file_field :image, :class=>"fondo"%>
    </div>

    <br>
    <div class= "up">
        <%= form.submit%>
    </div>
<% end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Movies Marvel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<br><br>
  <body>
    <div>
        <button><%= link_to 'Log in', destroy_user_session_path, method: :delete, class: "up" %></button>
        <button><%= link_to 'Sign up', new_user_registration_path, class: "up" %></button> 
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
        <% tv_show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_field :release_date %>
  </div>

  <div class="field">
      <%= form.collection_select(:nationality_id, Nationality.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%#= form.collection_select(:genre_ids, Genre.all, :id, :name,{ prompt: true }, { multiple: true }) %>
    <%= form.collection_check_boxes :genre_ids, Genre.all, :id, :name %>
    <%#= form.collection_radio_buttons :genre_ids, Genre.all, :id, :name %>
  </div>

  <br>

  <div class="actions up">
    <button><%= form.submit %></button>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<br><br><br><br><br>
<div>
<button><%= link_to 'Home', tv_shows_path%></button>
</div>
<div class="New_movies">
<h1 class="titulo">Editing Movies</h1>
  <!-- Content here -->
  <%= render 'form', tv_show: @tv_show%>

<button><%= link_to 'Show', @tv_show, class: "up"%></button>
<br> <br>
</div>

app/views/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="title">
    <h1>THE MOVIES MARVEL!!</h1>
    <a target="_blank" class="white-mode"></a>
      <div>
        <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1654801828/marvel/Cronologi%CC%81a_zlx5fy.jpg", class: "img-thumbnail" %>   
        <%= image_tag "https://res.cloudinary.com/maravoly/image/upload/v1654918237/marvel/puntos_nqoshp.png", class: "punto" %> 
      </div> 
  </div>

<div class="col-md-z">
    <% if user_signed_in? %>
      <% @tv_shows.each do |tv_show| %> 
        <div class="col-md-y">
          <div class="col-md-w">
            <div class="col-md-x">
              <%= image_tag tv_show.image_url%>    
              <p class="tx"><%= tv_show.name %></p>
              <p class="sumary"><%= tv_show.summary %></p>
              <p class="date"><%= tv_show.release_date.strftime("%Y") %></p>
              <p><%= image_tag(url_for(tv_show.nationality.flag_img)) %></p>
           </div>  
          </div> 
          <div class="col-md-v">
            <% if user_signed_in? %>
              <button><%= link_to 'Show', tv_show, class: "up" %></button>
            <% end %>
                <% if (user_signed_in? && (current_user == tv_show.user)) %>
                  <button><%= link_to 'Edit', edit_tv_show_path(tv_show), class: "up" %></button>
                  <button><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' }, class: "up" %></button></div>
                  <% elsif user_signed_in? && current_user.admin? %>
                  <p><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></p>
                  <% end %>
                <% end %>               
    <% end %>    
          </div>  
        </div> 
        
  <div>
    <% if user_signed_in? %>
      <button><%= link_to 'New Movie', new_tv_show_path, class: "up" %></button>
    <% end %>
  </div>
  

app/views/tv_shows/new.html.erb
<br><br><br>

<div>
<button><%= link_to 'Home', tv_shows_path%></button>
</div>

<div class="New_movies">
    <h1  class="titulo" style="width:700px">New Movies</h1><br>
    <h3>A New Film Enters</h3>
    <%= render 'form', tv_show: @tv_show %>
</div>

app/views/tv_shows/show.html.erb
<br><br>
<div class="up">
<button><%= link_to 'Home', tv_shows_path%></button>
</div>

<div class="cont">
    <p id="notice"><%= notice %></p>

    <p>
        <strong class="tx">Name:</strong>     
        <%= @tv_show.name %>
    </p> 

    <p>
        <strong class="tx">Summary:</strong>     
        <%= @tv_show.summary %>
    </p>
        
    <p>
        <strong class="tx">Release date:</strong>      
        <%= @tv_show.release_date.strftime("%Y") %>
    </p>
        
    <p>
        <strong class="tx">Nationality:</strong>
        <%= image_tag(url_for(@tv_show.nationality.flag_img)) %>
    </p>

    <div class="container">
        <h2>Listado de Episodios</h2><br>
        <% @tv_show.episodes.each do |episode| %>
            <p>
                <strong class="tx">Episode number:</strong>
                <%= episode.episode_number %>
            </p>

            <p>
                <strong class="tx">Title:</strong>
                <%= episode.title %>
            </p>

            <p>
                <strong class="tx">Summary:</strong>
                <%= episode.summary %>
            </p>
        <% end %>
    </div>

    <!--app/views/tv_shows/show.html.erb-->
    <h2><strong>Actors:</strong></h2>
    <ul>
        <% if @tv_show.actors %>
            <% @tv_show.actors.each do |actor|%>
                <li><strong><%= actor.id %>: </strong><%= "#{actor.first_name} #{actor.last_name}" %></li>
                <% if actor.image.attached? %>
                    <li><%= image_tag(actor.image, size: '150x200') %></li>
                <% end %>
            <% end %>
        <% else %>
            <% 'No Actors Added!!!'%>
        <% end %>
    </ul>

    <p><strong>Genres:</strong></p>
    <ul>
        <% if @tv_show.genres %>
            <% @tv_show.genres.each do |genre|%>
            <li><strong><%= "#{genre.id}" %>: </strong><%= genre.name %></li>
        <% end %>
        <% else %>
            <% 'No Genres Added!!!'%>
        <% end %>
    </ul>
</div>

<hr class= "linea">

 <!-- ... -->
<div class="container">
    <h2>Agregue un episodio:</h2>
    <%= form_with model: [ @tv_show, @tv_show.episodes.build ] do |form| %>
        <p>
            <%= form.label :episode_number, :class=>"tx" %><br>
            <%= form.number_field :episode_number, :class=>"fondo" %>
        </p>
        <p>
            <%= form.label :title, :class=>"tx" %><br>
            <%= form.text_field :title, :class=>"fondo" %>
        </p>
        <p>
            <%= form.label :summary, :class=>"tx" %><br>
            <%= form.text_area :summary, :class=>"fondo" %>
        </p>
        <p>
            <button><%= form.submit "Crear episodio", class: "up"%></button>
        </p>
    <% end %>
</div>

<button><%= link_to 'Add actors', new_tv_show_actor_path(@tv_show), class: "up" %></button> |
<button><%= link_to 'Edit', edit_tv_show_path(@tv_show), class: "up" %></button> 